### ISSUE TITLE
Crash when externally changing authorization

### ISSUE THREAD

**Issue by komocode** [heardrwt/RHAddressBook#20]
Downloaded and crashed using RHAddressBookTester target on a REAL device.
Steps to reproduce:
1. Launch Tester in device
2. Goto Settings App, change the authorization for Tester app to use Address Book to off
3. Crash on main()

Nothing in logs show any trace of what happened.

**Comment by heardrwt** [comment]
Can you give me a little more info re the crash.

Device? 
OS version?

Actual crash log.

Thanks.

**Comment by komocode** [comment]
iPhone 5
iOS 6.0.2

I'm not seeing any crash logs and I don't see any logs printed in console, but I've noticed the app does not resume where it left off when changing the privacy settings.

**Comment by heardrwt** [comment]
Looks like the system kills a running application upon flicking the switch from On -> Off.
I can reproduce this with any app using contacts on iOS 6. 

See: 
Dec 21 14:20:47 rPhone com.apple.launchd[1](UIKitApplication:com.rheard.RHAddressBookTester[0x930c][1220]) <Notice>: (UIKitApplication:com.rheard.RHAddressBookTester[0x930c]) Exited: Killed: 9
Dec 21 14:20:47 rPhone backboardd[52] <Warning>: Application 'UIKitApplication:com.rheard.RHAddressBookTester[0x930c]' exited abnormally with signal 9: Killed: 9

and 

Dec 21 14:22:05 rPhone com.apple.launchd[1](UIKitApplication:com.path.Path[0x6ff0][1226]) <Notice>: (UIKitApplication:com.path.Path[0x6ff0]) Exited: Killed: 9
Dec 21 14:22:05 rPhone backboardd[52] <Warning>: Application 'UIKitApplication:com.path.Path[0x6ff0]' exited abnormally with signal 9: Killed: 9

This is quite likely by design, however i'll open a radar.

**Comment by heardrwt** [comment]
Filed radar://12922532
