### ISSUE TITLE
Crash when trying to save Instant Message multivalue

### ISSUE THREAD

**Issue by danielrhodes** [heardrwt/RHAddressBook#22]
Here's the crash:

```
2013-01-08 01:17:51.775 XXXX[2851:50d7] -[__NSCFString count]: unrecognized selector sent to instance 0x1fb025c0
2013-01-08 01:17:51.776 XXXX[2851:50d7] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString count]: unrecognized selector sent to instance 0x1fb025c0'
```

Here's the associated code:

``` objective-c
RHMultiStringValue *imMultiValue = [person instantMessageServices];
RHMutableMultiStringValue *mutableIMMultiValue = [imMultiValue mutableCopy];
if (! mutableIMMultiValue) mutableIMMultiValue = [[RHMutableMultiStringValue alloc] initWithType:kABMultiStringPropertyType];
[mutableIMMultiValue addValue: stringVar withLabel: RHPersonInstantMessageUsernameKey];
person.instantMessageServices = mutableIMMultiValue;
[person save];
```

I noticed that it behaves better by not crashing if I pass in a string literal as the value (the string I am using comes from a string decoded from JSON). However, the value is never added, only the label.

**Comment by heardrwt** [comment]
The crash is caused by corrupting the AddressBook database by saving strings to a property of type RHMultiDictionaryValue. 

Each entry needs to be a dictionary with 2 key value pairs, service type + username.

You will need to remove any already corrupted entries from your addressbook, otherwise you will continue to hit strange issues when trying to access im hashes etc.
